### ISSUE TITLE
[question] why rust?

### ISSUE THREAD

**Issue by fuzzylemma** [ava-labs/avalanche-ops#17]
for aws infra provisioning, why was this in implemented in rust as opposed to using existing cloud provisioning tooling (terraform and/or ansible)?

**Comment by gyuho** [comment]
The goal is to build "one" single binary that creates all resources required to set up avalanche network. Under the hood, it uses CloudFormation for provision AWS resources, which is arguably better than Terraform, and does not require anything external (e.g., terraform binary).

**Comment by fuzzylemma** [comment]
gotcha, so portability is the priority?

**Comment by gyuho** [comment]
> gotcha, so portability is a top priority?

Yes, we plan to support other providers (bare metal machines).
