### ISSUE TITLE
Making ssh command run non-blocking

### ISSUE THREAD

**Issue by gyuho** [ava-labs/avalanche-ops#384]
https://github.com/ava-labs/avalanche-ops/blob/1631a68ad18a87eac3dd31b9eb5b00ba4b6b7c5c/avalancheup-aws/src/apply/mod.rs#L1441-L1453

this can block forever if VPC security group has wrong IP for SSH 22 port ingress traffic.

We should either automatically fix the VPC security group or make this non-blocking (just warn after 10-second)

**Comment by exdx** [comment]
I believe the referenced PR addressed this particular issue and we can close?
